//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikumAB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KontaktiTyyp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KontaktiTyyp()
        {
            this.Kontaktid = new HashSet<Kontaktid>();
        }
    
        public int KontaktiTyypId { get; set; }
        public string Nimi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontaktid> Kontaktid { get; set; }
    }
}
